CREATE TABLE IF NOT EXISTS stock_position (
    id BIGINT NOT NULL AUTO_INCREMENT,
    stock_code VARCHAR(20) NOT NULL COMMENT '股票代码',
    stock_name VARCHAR(50) DEFAULT NULL COMMENT '股票名称',
    direction VARCHAR(10) DEFAULT 'LONG' COMMENT '方向: LONG/SHORT',
    buy_price DECIMAL(10,3) NOT NULL COMMENT '买入价格',
    buy_date DATE NOT NULL COMMENT '买入日期',
    quantity INT NOT NULL DEFAULT 0 COMMENT '持仓数量(股)',
    current_price DECIMAL(10,3) DEFAULT NULL COMMENT '当前价格(收盘后更新)',
    market_value DECIMAL(15,2) DEFAULT NULL COMMENT '当前市值',
    cost_value DECIMAL(15,2) DEFAULT NULL COMMENT '成本市值',
    profit_loss DECIMAL(15,2) DEFAULT NULL COMMENT '浮动盈亏',
    profit_loss_pct DECIMAL(10,4) DEFAULT NULL COMMENT '盈亏比例%',
    stop_loss_price DECIMAL(10,3) DEFAULT NULL COMMENT '止损价',
    take_profit_price DECIMAL(10,3) DEFAULT NULL COMMENT '止盈价',
    source VARCHAR(20) DEFAULT 'MANUAL' COMMENT '来源: MANUAL/RECOMMENDATION/LLM',
    notes TEXT DEFAULT NULL COMMENT '备注',
    status VARCHAR(10) DEFAULT 'OPEN' COMMENT '状态: OPEN/CLOSED',
    sell_price DECIMAL(10,3) DEFAULT NULL COMMENT '卖出价格',
    sell_date DATE DEFAULT NULL COMMENT '卖出日期',
    realized_pl DECIMAL(15,2) DEFAULT NULL COMMENT '已实现盈亏',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_stock (stock_code, status),
    KEY idx_status (status),
    KEY idx_buy_date (buy_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='持仓记录';
